export const DUBAI_PLACES = [
  "Abu Hail",
  "Al Awir First",
  "Al Awir Second",
  "Al Bada",
  "Al Baraha",
  "Al Barsha First",
  "Al Barsha Second",
  "Al Barsha South First",
  "Al Barsha South Second",
  "Al Barsha South Third",
  "Al Barsha Third",
  "Al Buteen",
  "Al Dhagaya",
  "Al Garhoud",
  "Al Guoz Fourth",
  "Al Hamriya, Dubai",
  "Al Hamriya Port",
  "Al Hudaiba",
  "Al Jaddaf",
  "Al Jafiliya",
  "Al Karama",
  "Al Khabisi",
  "Al Khwaneej First",
  "Al Khwaneej Second",
  "Al Kifaf",
  "Al Mamzar",
  "Al Manara",
  "Al Mankhool",
  "Al Merkad",
  "Al Mina",
  "Al Mizhar First",
  "Al Mizhar Second",
  "Al Muraqqabat",
  "Al Murar",
  "Al Mushrif",
  "Al Muteena",
  "Al Nahda First",
  "Al Nahda Second",
  "Al Nasr, Dubai",
  "Al Quoz First",
  "Al Quoz Industrial First",
  "Al Quoz Industrial Fourth",
  "Al Quoz Industrial Second",
  "Al Quoz Industrial Third",
  "Al Quoz Second",
  "Al Quoz Third",
  "Al Qusais First",
  "Al Qusais Industrial Fifth",
  "Al Qusais Industrial First",
  "Al Qusais Industrial Fourth",
  "Al Qusais Industrial Second",
  "Al Qusais Industrial Third",
  "Al Qusais Second",
  "Al Qusais Third",
  "Al Raffa",
  "Al Ras",
  "Al Rashidiya",
  "Al Rigga",
  "Al Sabkha",
  "Al Safa First",
  "Al Safa Second",
  "Al Safouh First",
  "Al Safouh Second",
  "Al Satwa",
  "Al Shindagha",
  "Al Souq Al Kabeer",
  "Al Twar First",
  "Al Twar Second",
  "Al Twar Third",
  "Al Warqa'a Fifth",
  "Al Warqa'a First",
  "Al Warqa'a Fourth",
  "Al Warqa'a Second",
  "Al Warqa'a Third",
  "Al Wasl",
  "Al Waheda",
  "Ayal Nasir",
  "Aleyas",
  "Business Bay",
  "Bu Kadra",
  "Downtown Dubai",
  "Dubai Investment park First",
  "Dubai Investment Park Second",
  "Emirates Hill First",
  "Emirates Hill Second",
  "Emirates Hill Third",
  "Hatta",
  "Hor Al Anz",
  "Hor Al Anz East",
  "Jebel Ali 1",
  "Jebel Ali 2",
  "Jebel Ali Industrial",
  "Jebel Ali Palm",
  "Jumeira First",
  "Palm Jumeira",
  "Jumeira Second",
  "Jumeira Third",
  "Marsa Dubai",
  "Mirdif",
  "Muhaisanah Fourth",
  "Muhaisanah Second",
  "Muhaisanah Third",
  "Muhaisnah First",
  "Nad Al Hammar",
  "Nadd Al Shiba Fourth",
  "Nadd Al Shiba Second",
  "Nadd Al Shiba Third",
  "Nad Shamma",
  "Naif",
  "Port Saeed",
  "Arabian Ranches",
  "Oud Al Muteena Third",
  "Ras Al Khor",
  "Ras Al Khor Industrial First",
  "Ras Al Khor Industrial Second",
  "Ras Al Khor Industrial Third",
  "Rigga Al Buteen",
  "Trade Centre 1",
  "Trade Centre 2",
  "Umm Al Sheif",
  "Umm Hurair First",
  "Umm Hurair Second",
  "Umm Ramool",
  "Umm Suqeim First",
  "Umm Suqeim Second",
  "Umm Suqeim Third",
  "Wadi Alamardi",
  "Warsan First",
  "Warsan Second",
  "Yaraah",
  "Za'abeel First",
  "Za'abeel Second",
];

export const MEALS_LIST = [
  "Bacon, egg and cheese sandwich",
  "Breakfast burrito",
  "Buttermilk pancakes",
  "Grits",
  "Chicken and waffles",
  "Key lime pie",
  "Sourdough bread",
  "S'mores",
  "Twinkies",
  "Burger",
  "The classic hot dog",
  "The cheeseburger",
  "Reuben sandwich",
  "Barbecue ribs",
  "The BLT",
  "Apple pie",
  "Philly Cheesesteak",
  "California roll",
  "Beef jerky",
  "Buffalo chicken wings",
  "Baked Alaska",
  "Meatloaf",
  "Macaroni and cheese",
  "Fajitas",
  "Chicago's deep dish pizza",
  "Thanksgiving turkey dinner",
  "Tater Tots",
  "Baked beans",
  "Wild Alaskan salmon",
  "Grilled cheese sandwich",
  "Cornbread",
  "Cheesecake",
  "Bamia",
  "Besarah",
  "‘Eggah",
  "Fattah",
  "Fesikh",
  "Feteer",
  "Ful medames",
  "Hamam mahshi",
  "Hawawshi",
  "Kabab",
  "Kamounia",
  "Kaware‘",
  "Kersha",
  "Keshk",
  "Kofta",
  "Kushari",
  "Macaroni béchamel",
  "Mahshi",
  "Mesaqa‘ah",
  "Molokhiya",
  "Mombar",
  "Rozz me‘ammar",
  "Sabanekh",
  "Sayadiya",
  "Shakshouka",
  "Shawerma",
  "Torly",
  "Qolqas",
  "Halwa poori",
  "Sajji",
  "Zarda",
  "Seekh kabab",
  "Chaat",
  "Paratha",
  "Chapli kabab",
  "Chicken karahi",
  "Nihari",
  "Samosa",
  "View more",
  " Pizza",
  " Bottarga",
  " Lasagna",
  " Fiorentina Steak",
  " Ribollita",
  " Polenta",
  " Ossobuco",
  " Risotto",
  " Carbonara",
  " Truffles",
  " Focaccia (and other bread)",
  " Arancini & Supplì",
  " Coffee",
  " Gelato",
  " Tiramisu",
  " Digestivo",
  "Murg Makhani (Butter Chicken)",
  "Instant Pot Butter Chicken",
  "Tandoori Chicken",
  "Chicken Tikka Masala",
  "Chicken Vindaloo Curry",
  "Rogan Josh (Red Lamb)",
  "Malai Kofta",
  "Chole (Chickpea Curry)",
  "Palak Paneer (Spinach and Cottage Cheese)",
  "Kaali Daal (Black Lentils)",
  "Papdi Chaat",
  "Naan (Leavened Indian Flatbread)",
];
